"Resource/UI/CreateLobbyFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"		"Panel"
		"fieldName"			"PnlBackground"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"-1"
		"wide"				"156"
		"tall"				"45"
		"visible"			"1"
		"enabled"			"1"
		"paintbackground"	"1"
		"paintborder"		"1"
	}
	
	"BtnStartCampaign"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnStartCampaign"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"navUp"					"BtnStartVersus"
		"navDown"				"BtnStartVersus"
		"tooltiptext"			"#L4D360UI_FoundGames_Start_Campaign_Tip"
		"labelText"				"#L4D360UI_FoundGames_Start_Campaign"
		"style"					"FlyoutMenuButton"
		"command"				"StartCampaign"
	}

	"BtnStartVersus"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnStartVersus"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"navUp"					"BtnStartCampaign"
		"navDown"				"BtnStartCampaign"
		"tooltiptext"			"#L4D360UI_FoundGames_Start_Versus_Tip"
		"labelText"				"#L4D360UI_FoundGames_Start_Versus"
		"style"					"FlyoutMenuButton"
		"command"				"StartVersus"
	}
}