"Resource/UI/DropDownHospital.res"
{
	"PnlBackground"
	{
		"ControlName"		"Panel"
		"fieldName"			"PnlBackground"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"-1"
		"wide"				"156"
		"tall"				"105"
		"visible"			"1"
		"enabled"			"1"
		"paintbackground"	"1"
		"paintborder"		"1"
	}

	"BtnApartments"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnApartments"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRooftop"
		"navDown"				"BtnSubway"
		"labelText"				"#L4D360UI_Chapter_Apartment"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Apartment"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Apartment_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Apartment"
	}	
	
	"BtnSubway"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSubway"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnApartments"
		"navDown"				"BtnSewers"
		"labelText"				"#L4D360UI_Chapter_Subway"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Subway"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Subway_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Subway"
	}	
	
	"BtnSewers"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSewers"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSubway"
		"navDown"				"BtnHospital"
		"labelText"				"#L4D360UI_Chapter_Sewers"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Sewers"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Sewers_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Sewers"
	}	
		
	"BtnHospital"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHospital"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSewers"
		"navDown"				"BtnRooftop"
		"labelText"				"#L4D360UI_Chapter_Hospital"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Hospital"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Hospital_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Hospital"
	}	
	
	"BtnRooftop"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRooftop"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHospital"
		"navDown"				"BtnApartments"
		"labelText"				"#L4D360UI_Chapter_Rooftop"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Rooftop"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Rooftop_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Rooftop"
	}
}