"Resource/UI/DropDownAirport.res"
{
	"PnlBackground"
	{
		"ControlName"		"Panel"
		"fieldName"			"PnlBackground"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"-1"
		"wide"				"156" [$ENGLISH]
		"wide"				"186" [$!ENGLISH]
		"tall"				"105"
		"visible"			"1"
		"enabled"			"1"
		"paintbackground"	"1"
		"paintborder"		"1"
	}

	"BtnGreenhouse"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnGreenhouse"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRunway"
		"navDown"				"BtnOffices"
		"labelText"				"#L4D360UI_Chapter_Greenhouse"
		"tooltiptext"			"#L4D360UI_Chapter_Greenhouse_Tooltip"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Greenhouse_Tooltip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Greenhouse"
	}	
	
	"BtnOffices"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnOffices"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnGreenhouse"
		"navDown"				"BtnGarage"
		"labelText"				"#L4D360UI_Chapter_Offices"
		"tooltiptext"			"#L4D360UI_Chapter_Offices_Tooltip"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Offices_Tooltip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Offices"
	}	
	
	"BtnGarage"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnGarage"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnOffices"
		"navDown"				"BtnAirport"
		"labelText"				"#L4D360UI_Chapter_Garage"
		"tooltiptext"			"#L4D360UI_Chapter_Garage_Tooltip"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Garage_Tooltip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Garage"
	}	
		
	"BtnAirport"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAirport"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnGarage"
		"navDown"				"BtnRunway"
		"labelText"				"#L4D360UI_Chapter_Airport"
		"tooltiptext"			"#L4D360UI_Chapter_Airport_Tooltip"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Airport_Tooltip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Airport"
	}	
	
	"BtnRunway"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRunway"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAirport"
		"navDown"				"BtnGreenhouse"
		"labelText"				"#L4D360UI_Chapter_Runway"
		"tooltiptext"			"#L4D360UI_Chapter_Runway_Tooltip"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Runway_Tooltip_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Runway"
	}
}