"Resource/UI/DropDownSmallTown.res"
{
	"PnlBackground"
	{
		"ControlName"		"Panel"
		"fieldName"			"PnlBackground"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"-1"
		"wide"				"156"
		"tall"				"105"
		"visible"			"1"
		"enabled"			"1"
		"paintbackground"	"1"
		"paintborder"		"1"
	}

	"BtnCaves"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnCaves"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnBoat"
		"navDown"				"BtnDrainage"
		"labelText"				"#L4D360UI_Chapter_Caves"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Caves"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Caves_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Caves"
	}	
	
	"BtnDrainage"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnDrainage"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnCaves"
		"navDown"				"BtnSmallTown"
		"labelText"				"#L4D360UI_Chapter_Drainage"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Drainage"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Drainage_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Drainage"
	}	
	
	"BtnSmallTown"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSmallTown"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnDrainage"
		"navDown"				"BtnMainStreet"
		"labelText"				"#L4D360UI_Chapter_Smalltown"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_SmallTown"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_SmallTown_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Smalltown"
	}	
		
	"BtnMainStreet"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnMainStreet"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSmallTown"
		"navDown"				"BtnBoat"
		"labelText"				"#L4D360UI_Chapter_MainStreet"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_MainStreet"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_MainStreet_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_MainStreet"
	}	
	
	"BtnBoat"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnBoat"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnMainStreet"
		"navDown"				"BtnCaves"
		"labelText"				"#L4D360UI_Chapter_Boat"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Boat"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Boat_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Boat"
	}
}