"Resource/UI/DropDownFarm.res"
{
	"PnlBackground"
	{
		"ControlName"		"Panel"
		"fieldName"			"PnlBackground"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"-1"
		"wide"				"156" [$ENGLISH]
		"wide"				"176" [$!ENGLISH]
		"tall"				"105"
		"visible"			"1"
		"enabled"			"1"
		"paintbackground"	"1"
		"paintborder"		"1"
	}

	"BtnHilltop"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHilltop"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFarm"
		"navDown"				"BtnTrainTunnel"
		"labelText"				"#L4D360UI_Chapter_Hilltop"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Hilltop"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Hilltop_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Hilltop"
	}	
	
	"BtnTrainTunnel"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnTrainTunnel"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHilltop"
		"navDown"				"BtnBridge"
		"labelText"				"#L4D360UI_Chapter_TrainTunnel"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_TrainTunnel"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_TrainTunnel_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_TrainTunnel"
	}	
	
	"BtnBridge"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnBridge"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnTrainTunnel"
		"navDown"				"BtnBarn"
		"labelText"				"#L4D360UI_Chapter_Bridge"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Bridge"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Bridge_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Bridge"
	}	
		
	"BtnBarn"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnBarn"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnBridge"
		"navDown"				"BtnFarm"
		"labelText"				"#L4D360UI_Chapter_Barn"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Barn"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Barn_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Barn"
	}	
	
	"BtnFarm"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFarm"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnBarn"
		"navDown"				"BtnHilltop"
		"labelText"				"#L4D360UI_Chapter_Farm"
		"tooltiptext"			"#L4D360UI_Chapter_Tooltip_Farm"
		"disabled_tooltiptext"	"#L4D360UI_Chapter_Tooltip_Farm_Disabled"
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Chapter_Farm"
	}
}