"Resource/UI/DropDownCharacters.res"
{
	"PnlBackground"
	{
		"ControlName"		"Panel"
		"fieldName"			"PnlBackground"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"1"
		"wide"				"156" [$ENGLISH]
		"wide"				"166" [$!ENGLISH]
		"tall"				"105"
		"visible"			"1"
		"enabled"			"1"
		"paintbackground"	"1"
		"paintborder"		"1"
	}

	"BtnNamVet"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnNamVet"
		"xpos"					"80"
		"ypos"					"0"
		"zpos"					"2"
		"wide"					"70"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRandom"
		"navDown"				"BtnTeenGirl"
		"labelText"				"#L4D360UI_NamVet"
		"tooltiptext"			""
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_NamVet"
	}	
	
	"BtnTeenGirl"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnTeenGirl"
		"xpos"					"80"
		"ypos"					"20"
		"zpos"					"2"
		"wide"					"70"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnNamVet"
		"navDown"				"BtnBiker"
		"labelText"				"#L4D360UI_TeenGirl"
		"tooltiptext"			""
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_TeenGirl"
	}	
	
	"BtnBiker"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnBiker"
		"xpos"					"80"
		"ypos"					"40"
		"zpos"					"2"
		"wide"					"70"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnTeenGirl"
		"navDown"				"BtnManager"
		"labelText"				"#L4D360UI_Biker"
		"tooltiptext"			""
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Biker"
	}	
		
	"BtnManager"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnManager"
		"xpos"					"80"
		"ypos"					"60"
		"zpos"					"2"
		"wide"					"70"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnBiker"
		"navDown"				"BtnRandom"
		"labelText"				"#L4D360UI_Manager"
		"tooltiptext"			""
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Manager"
	}
	
	"BtnRandom"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRandom"
		"xpos"					"80"
		"ypos"					"80"
		"zpos"					"2"
		"wide"					"70"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnManager"
		"navDown"				"BtnNamVet"
		"labelText"				"#L4D360UI_Random"
		"tooltiptext"			""
		"style"					"FlyoutMenuButton"
		"command"				"#L4D360UI_Random"
	}	
	
	"HeroPortraitBack"
	{
		"ControlName"			"Panel"
		"fieldName"				"HeroPortraitBack"
		"xpos"					"10"
		"ypos"					"18"
		"zpos"					"4"
		"wide"					"68"
		"tall"					"68"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"bgcolor_override"		"80 80 80 255"
	}
	"HeroPortrait"
	{
		"ControlName"			"ImagePanel"
		"fieldName"				"HeroPortrait"
		"image"					"select_Random"
		"xpos"					"12"
		"ypos"					"20"
		"zpos"					"5"
		"wide"					"64"
		"tall"					"64"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"scaleimage"			"1"
	}
}