"Resource/UI/InGameOptionsFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"156"
		"tall"					"45"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnReturnToLobby"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnReturnToLobby"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"navUp"					"BtnBootPlayer"
		"navDown"				"BtnBootPlayer"
		"tooltiptext"			"#L4D360UI_ReturnToLobby_Tip"
		"labelText"				"#L4D360UI_ReturnToLobby"
		"style"					"FlyoutMenuButton"
		"command"				"ReturnToLobby"
	}
	
	"BtnBootPlayer"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnBootPlayer"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"navUp"					"BtnReturnToLobby"
		"navDown"				"BtnReturnToLobby"
		"tooltiptext"			"#L4D360UI_BootPlayer_Tip"
		"labelText"				"#L4D360UI_BootPlayer"
		"style"					"FlyoutMenuButton"
		"command"				"BootPlayer"
	}
}