"Resource/UI/InGameDifficultySelect.res"
{
	"InGameDifficultySelect"
	{
		"ControlName"			"Frame"
		"fieldName"			"InGameDifficultySelect"
		"xpos"				"c-200" [$ENGLISH]
		"xpos"				"c-225" [$!ENGLISH]
		"ypos"				"c-80"
		"wide"				"400" [$ENGLISH]
		"wide"				"450" [$!ENGLISH]
		"tall"				"165"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"			"0"
		"usetitlesafe"			"1"
	}
	
	"LblDifficultyTitle"
	{
		"ControlName"				"Label"
		"fieldName"					"LblDifficultyTitle"
		"xpos"						"10"
		"ypos"						"10"
		"wide"						"f0"
		"wrap"						"1"
		"autoResize"				"1"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"proportionalToParent"		"1"
		"usetitlesafe"				"0"
		"Font"						"FrameTitle"
		"LabelText"					"#L4D360UI_InGameDifficultySelect"
	}

	"LblDescription"
	{
		"ControlName"				"Label"
		"fieldName"					"LblDescription"
		"xpos"						"10"
		"ypos"						"33"
		"wide"						"f0"
		"wrap"						"1"
		"autoResize"				"1"
		"pinCorner"					"0"
		"visible"					"0"
		"enabled"					"1"
		"tabPosition"				"0"
		"proportionalToParent"		"1"
		"usetitlesafe"				"0"
		"Font"						"Default"
		"fgcolor_override"          "MediumGray"
		"LabelText"					"#L4D360UI_Difficulty_Description"
	}
		
	"LblCurrentDifficulty"
	{
		"ControlName"				"Label"
		"fieldName"					"LblCurrentDifficulty"
		"xpos"						"15"
		"ypos"						"35"
		"wide"						"f0"
		"wrap"						"1"
		"autoResize"				"1"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"proportionalToParent"		"1"
		"usetitlesafe"				"0"
		"Font"						"DefaultLarge"
		"fgcolor_override"          "MediumGray"
		"LabelText"					""
	}

	"BtnEasy"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnEasy"
		"ypos"					"65"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"1"
		"wrap"					"1"
		"navUp"					"BtnImpossible"
		"navDown"				"BtnNormal"
		"labelText"				"#L4D360UI_Difficulty_Easy"
		"tooltiptext"				"#L4D360UI_Difficulty_Tooltip_Easy"
		"style"					"DefaultButton"
		"command"				"Easy"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
	}


	
	"BtnNormal"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnNormal"
		"ypos"					"87"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnEasy"
		"navDown"				"BtnHard"
		"labelText"				"#L4D360UI_Difficulty_Normal"
		"tooltiptext"			"#L4D360UI_Difficulty_Tooltip_Normal"
		"style"					"DefaultButton"
		"command"				"Normal"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
	}
	
	"BtnHard"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHard"
		"ypos"					"109"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnNormal"
		"navDown"				"BtnImpossible"
		"labelText"				"#L4D360UI_Difficulty_Hard"
		"tooltiptext"			"#L4D360UI_Difficulty_Tooltip_Hard"
		"style"					"DefaultButton"
		"command"				"Hard"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
	}
	
	"BtnImpossible"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnImpossible"
		"ypos"					"132"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHard"
		"navDown"				"BtnEasy"
		"labelText"				"#L4D360UI_Difficulty_Impossible"
		"tooltiptext"			"#L4D360UI_Difficulty_Tooltip_Impossible"
		"style"					"DefaultButton"
		"command"				"Impossible"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
	}
}