"Resource/UI/InGameScenarioSelect.res"
{
	"InGameScenarioSelect"
	{
		"ControlName"			"Frame"
		"fieldName"			"InGameScenarioSelect"
		"xpos"				"c-200"
		"ypos"				"c-90"
		"wide"				"400"
		"tall"				"180"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"			"0"
		"usetitlesafe"			"1"
	}
	
	"LblGameTitle"
	{
		"ControlName"				"Label"
		"fieldName"					"LblGameTitle"
		"xpos"						"10"
		"ypos"						"10"
		"wide"						"f0"
		"wrap"						"1"
		"autoResize"				"1"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"proportionalToParent"		"1"
		"usetitlesafe"				"0"
		"Font"						"FrameTitle"
		"LabelText"					"#L4D360UI_StartNewCampaign"
	}

	"LblDescription"
	{
		"ControlName"				"Label"
		"fieldName"					"LblDescription"
		"xpos"						"10"
		"ypos"						"33"
		"wide"						"f0"
		"wrap"						"1"
		"autoResize"				"1"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"proportionalToParent"		"1"
		"usetitlesafe"				"0"
		"Font"						"Default"
		"fgcolor_override"          "MediumGray"
		"LabelText"					"#L4D360UI_StartNewCampaignConfMsg"
	}
	
	"LblCurrentScenario"
	{
		"ControlName"				"Label"
		"fieldName"					"LblCurrentScenario"
		"xpos"						"15"
		"ypos"						"53"
		"wide"						"f0"
		"wrap"						"1"
		"autoResize"				"1"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"proportionalToParent"		"1"
		"usetitlesafe"				"0"
		"Font"						"DefaultLarge"
		"fgcolor_override"          "MediumGray"
		"LabelText"					""
	}
	
	"BtnHospital"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHospital"
		"ypos"					"80"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"1"
		"wrap"					"1"
		"navUp"					"BtnFarm"
		"navDown"				"BtnSmallTown"
		"labelText"				"#L4D360UI_Campaign_Hospital"
		"tooltiptext"			"#L4D360UI_Campaign_Tooltip_Hospital"
		"disabled_tooltiptext"	"#L4D360UI_Campaign_Tooltip_Hospital"
		"style"					"DefaultButton"
		"command"				"Hospital"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}
	
	"BtnSmallTown"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSmallTown"
		"ypos"					"102"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHospital"
		"navDown"				"BtnAirport"
		"labelText"				"#L4D360UI_Campaign_SmallTown"
		"tooltiptext"			"#L4D360UI_Campaign_Tooltip_SmallTown"
		"disabled_tooltiptext"	"#L4D360UI_Campaign_Tooltip_SmallTown"
		"style"					"DefaultButton"
		"command"				"SmallTown"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}	
	
	"BtnAirport"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAirport"
		"ypos"					"124"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSmallTown"
		"navDown"				"BtnFarm"
		"labelText"				"#L4D360UI_Campaign_Airport"
		"tooltiptext"			"#L4D360UI_Campaign_Tooltip_Airport"
		"disabled_tooltiptext"	"#L4D360UI_Campaign_Tooltip_Airport"
		"style"					"DefaultButton"
		"command"				"Airport"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}
	
	"BtnFarm"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFarm"
		"ypos"					"146"
		"xpos"					"15"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAirport"
		"navDown"				"BtnHospital"
		"labelText"				"#L4D360UI_Campaign_Farm"
		"tooltiptext"			"#L4D360UI_Campaign_Tooltip_Farm"
		"disabled_tooltiptext"	"#L4D360UI_Campaign_Tooltip_Farm"
		"style"					"DefaultButton"
		"command"				"Farm"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}
}