"Resource/UI/Downloads.res"
{
	"LoadingProgress"
	{	
		"ControlName"			"Frame"
		"fieldName"				"LoadingProgress"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"f0"
		"tall"					"f0"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
	}

	"ProTotalProgress"
	{
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ProTotalProgress"
		"xpos"					"r220"
		"ypos"					"r60"
		"wide"					"150"
		"tall_hidef"			"10"
		"tall_lodef"			"13"
		"zpos"					"5"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
	}
	
	"WorkingAnim"
	{
		"ControlName"			"ImagePanel"
		"fieldName"				"WorkingAnim"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"5"
		"wide"					"40"
		"tall"					"40"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"scaleImage"			"1"
		"image"					"common/l4d_spinner"
	}	
	
	"LoadingText"
	{
		"ControlName"			"Label"
		"fieldName"				"LoadingText"
		"xpos"					"r270"
		"ypos"					"r80"
		"zpos"					"5"
		"wide"					"200"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"DefaultBold"
		"labelText"				"#L4D360UI_Loading"
		"textAlignment"			"east"
	}	
	
	"BGImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"BGImage"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f0"
		"tall"				"f0"
		"zpos"				"2"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"1"
	}
	
	"Poster"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"Poster"
		"xpos"				"c-240"
		"ypos"				"0"
		"wide"				"480"
		"tall"				"f0"
		"zpos"				"3"
		"scaleImage"		"1"
		"visible"			"0"
		"enabled"			"1"
		// APS: THESE ARE NOW DYNAMIC - DON"T PUT A DEFAULT IMAGE HERE!
		"image"				""
	}
	
	"LocalizedCampaignName"
	{
		"ControlName"			"Label"
		"fieldName"				"LocalizedCampaignName"
		"xpos"					"0"
		"ypos"					"395"
		"zpos"					"5"
		"wide"					"f0"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				""
		"textAlignment"			"south"
	}
	
	"LocalizedCampaignTagline"
	{
		"ControlName"			"Label"
		"fieldName"				"LocalizedCampaignTagline"
		"xpos"					"0"	[$!JAPANESE]
		"xpos"					"c-270"	[$JAPANESE]
		"ypos"					"100"
		"zpos"					"5"
		"wide"					"f0"	[$!JAPANESE]
		"wide"					"540"	[$JAPANESE]
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				""
		"textAlignment"			"south"
		"centerwrap"			"0"		[$!JAPANESE]
		"centerwrap"			"1"		[$JAPANESE]
	}
	
	"PlayerName1"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName1"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
	}	
	
	"PlayingAs1"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs1"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Bill"
		"textAlignment"			"north"
	}	
	
	"PlayerName2"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName2"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
	}	
	
	"PlayingAs2"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs2"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Zoey"
		"textAlignment"			"north"
	}
	
	"PlayerName3"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName3"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
	}	
	
	"PlayingAs3"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs3"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Francis"
		"textAlignment"			"north"
	}
	
	"PlayerName4"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName4"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
	}	
	
	"PlayingAs4"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs4"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"5"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Louis"
		"textAlignment"			"north"
	}
	
	"PlayerName1Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName1Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
		"fgcolor_override"		"0 0 0 255"
	}	
	
	"PlayingAs1Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs1Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Bill"
		"textAlignment"			"north"
		"fgcolor_override"		"0 0 0 255"
	}	
	
	"PlayerName2Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName2Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
		"fgcolor_override"		"0 0 0 255"
	}	
	
	"PlayingAs2Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs2Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Zoey"
		"textAlignment"			"north"
		"fgcolor_override"		"0 0 0 255"
	}
	
	"PlayerName3Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName3Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
		"fgcolor_override"		"0 0 0 255"
	}	
	
	"PlayingAs3Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs3Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Francis"
		"textAlignment"			"north"
		"fgcolor_override"		"0 0 0 255"
	}
	
	"PlayerName4Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayerName4Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"FrameTitle"
		"labelText"				"player 1 name"
		"textAlignment"			"south"
		"fgcolor_override"		"0 0 0 255"
	}	
	
	"PlayingAs4Shadow"
	{
		"ControlName"			"Label"
		"fieldName"				"PlayingAs4Shadow"
		"xpos"					"c0"
		"ypos"					"c0"
		"zpos"					"4"
		"wide"					"250"
		"tall"					"24"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Loading_As_Louis"
		"textAlignment"			"north"
		"fgcolor_override"		"0 0 0 255"
	}
}