"Resource/UI/MatchPrivacy.res"
{
	"MatchPrivacy"
	{
		"ControlName"				"Frame"
		"fieldName"					"MatchPrivacy"
		"xpos"						"c-200"
		"ypos"						"c-100"
		"wide"						"400"
		"tall"						"150"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
	}

	"LblDescription"
	{
		"ControlName"				"Label"
		"fieldName"					"LblDescription0"
		"xpos"						"-23"
		"ypos"						"5"
		"wide"						"f0"
		"wrap"						"1"
		"autoResize"				"1"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"proportionalToParent"		"1"
		"usetitlesafe"				"1"
		"Font"						"Default"
		"LabelText"					"#L4D360UI_Access_Description"
	}
	
	"BtnPublicGame"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnPublicGame"
		"ypos"					"25"
		"xpos"					"-31"
		"wide"					"230"
		"tall"					"20"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"1"
		"wrap"					"1"
		"navUp"					"BtnInviteOnly"
		"navDown"				"BtnFriendsOnly"
		"labelText"				"#L4D360UI_Access_Public"
		"tooltiptext"			"#L4D360UI_Access_Tooltip_Public"
		"style"					"DefaultButton"
		"command"				"Public"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}	
	
	"BtnFriendsOnly"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFriendsOnly"
		"xpos"					"-31"
		"ypos"					"50"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnPublicGame"
		"navDown"				"BtnLocalAreaNetwork"
		"labelText"				"#L4D360UI_Access_Friends"
		"tooltiptext"			"#L4D360UI_Access_Tooltip_Friends"
		"style"					"DefaultButton"
		"command"				"Friends"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}	
	
	"LblFriendsIcon"
	{
		"ControlName"			"Label"
		"fieldName"				"LblFriendsIcon"
		"xpos"					"r150"
		"ypos"					"45"
		"zpos"					"2"
		"wide"					"32"
		"tall"					"32"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"proportionalToParent"	"1"
		"usetitlesafe"			"1"
		"Font"					"GameUIButtons"
		"labelText"				"#GameUI_Icons_PARTY_LEADER"
	}
	
	"LblFriendsOnlineTxt"
	{
		"ControlName"			"Label"
		"fieldName"				"LblFriendsOnlineTxt"
		"xpos"					"r125"
		"ypos"					"45"
		"zpos"					"2"
		"wide"					"200"
		"tall"					"32"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"proportionalToParent"	"1"
		"usetitlesafe"			"1"
		"Font"					"Default"
		"labelText"				"#L4D360UI_Access_NumOnline"
	}
	
	"LblFriendsOnline"
	{
		"ControlName"			"Label"
		"fieldName"				"LblFriendsOnline"
		"xpos"					"350"
		"ypos"					"43"
		"zpos"					"2"
		"wide"					"200"
		"tall"					"32"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"proportionalToParent"	"1"
		"usetitlesafe"			"1"
		"Font"					"FrameTitle"
		"labelText"				"0"
	}
	
	"PnlFriendsUnderline"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlFriendsUnderline"
		"xpos"					"225"
		"ypos"					"95"
		"wide"					"f0"
		"tall"					"1"
		"bgColor_override"		"64 64 64 255"
	}
	
	"BtnLocalAreaNetwork"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLocalAreaNetwork"
		"xpos"					"-31"
		"ypos"					"75"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFriendsOnly"
		"navDown"				"BtnInviteOnly"
		"labelText"				"#L4D360UI_Access_LAN"
		"tooltiptext"			"#L4D360UI_Access_Tooltip_LAN"
		"style"					"DefaultButton"
		"command"				"LAN"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}	
	
	"BtnInviteOnly"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnInviteOnly"
		"xpos"					"-31"
		"ypos"					"100"
		"wide"					"230"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLocalAreaNetwork"
		"navDown"				"BtnPublicGame"
		"labelText"				"#L4D360UI_Access_Invite"
		"tooltiptext"			"#L4D360UI_Access_Tooltip_Invite"
		"style"					"DefaultButton"
		"command"				"Invite"
		"proportionalToParent"	"1"
		"usetitlesafe" 			"1"
		EnabledTextInsetX		"10"
		DisabledTextInsetX		"10"
		FocusTextInsetX			"10"
		OpenTextInsetX			"10"
	}	
	
}