"Resource/UI/MultiPlayer.res"
{
	"MultiPlayer"
	{
		"ControlName"		"Frame"
		"fieldName"		"MultiPlayer"
		"xpos"			"c-250"
		"ypos"			"c-150"
		"wide"			"500"
		"tall"			"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	
	"LblXboxLive"
	{
		"ControlName"		"Label"
		"fieldName"		"LblXboxLive"
		"xpos"			"15"
		"ypos"			"15"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
	}

	"BtnCreateLiveGame"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnCreateLiveGame"
		"xpos"			"15"
		"ypos"			"45"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"			"BtnFindSystemLinkGame"
		"navDown"		"BtnFindLiveGame"
		"tooltiptext"		"#L4D360UI_MultiPlayer_CreateLiveGame"
	}

	"BtnFindLiveGame"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnFindLiveGame"
		"xpos"			"15"
		"ypos"			"75"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"			"BtnCreateLiveGame"
		"navDown"		"BtnCreateSystemLinkGame"
		"tooltiptext"		"#L4D360UI_MultiPlayer_FindLiveGame"
	}

	"LblSystemLink"
	{
		"ControlName"		"Label"
		"fieldName"		"LblSystemLink"
		"xpos"			"15"
		"ypos"			"125"
		"wide"			"165"
		"tall"			"25"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
	}

	"BtnCreateSystemLinkGame"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnCreateSystemLinkGame"
		"xpos"			"15"
		"ypos"			"135"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"		"BtnFindLiveGame"
		"navDown"		"BtnFindSystemLinkGame"
		"tooltiptext"		"#L4D360UI_MultiPlayer_CreateSystemLinkGame"
	}

	"BtnFindSystemLinkGame"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnFindSystemLinkGame"
		"xpos"			"15"
		"ypos"			"165"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"		"BtnCreateSystemLinkGame"
		"navDown"		"BtnCreateLiveGame"
		"tooltiptext"		"#L4D360UI_MultiPlayer_FindSystemLinkGame"
	}
}