"Resource/UI/Options.res"
{
	"Options"
	{
		"ControlName"		"Frame"
		"fieldName"		"Options"
		"xpos"			"c-250"
		"ypos"			"c-150"
		"wide"			"500"
		"tall"			"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"usetitlesafe"	"1"
	}

	"BtnGame"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnGame"
		"xpos"			"15"
		"ypos"			"15"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"			"BtnCredits"
		"navDown"		"BtnAudioVideo"
		"tooltiptext"		"#L4D360UI_Options_Game"
	}

	"BtnAudioVideo"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnAudioVideo"
		"xpos"			"15"
		"ypos"			"45"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"			"BtnGame"
		"navDown"		"BtnController"
		"tooltiptext"		"#L4D360UI_Options_AudioVideo"
	}

	"BtnController"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnController"
		"xpos"			"15"
		"ypos"			"75"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"			"BtnAudioVideo"
		"navDown"		"BtnStorage"
		"tooltiptext"		"#L4D360UI_Options_Controller"
	}

	"BtnStorage"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnStorage"
		"xpos"			"15"
		"ypos"			"105"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"			"BtnController"
		"navDown"		"BtnCredits"
		"tooltiptext"		"#L4D360UI_Options_Storage"
	}

	"BtnCredits"
	{
		"ControlName"		"ImageButton"
		"fieldName"		"BtnCredits"
		"xpos"			"15"
		"ypos"			"135"
		"wide"			"256"
		"tall"			"64"
		"autoResize"		"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"proportionalToParent"	"1"
		"navUp"			"BtnStorage"
		"navDown"		"BtnGame"
		"tooltiptext"		"#L4D360UI_Options_Credits"
	}
}