"Resource/UI/OptionsFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"		"Panel"
		"fieldName"			"PnlBackground"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"-1"
		"wide"				"156"
		"tall"				"65" [$X360]
		"tall"				"65" [$WIN32]
		"visible"			"1"
		"enabled"			"1"
		"paintbackground"	"1"
		"paintborder"		"1"
	}

	"BtnAudioVideo"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAudioVideo"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"navUp"					"BtnStorage"
		"navDown"				"BtnController"
		"tooltiptext"			"#L4D360UI_Options_AudioVideo"
		"disabled_tooltiptext"	"#L4D360UI_Options_AudioVideo_Disabled"
		"labelText"				"#L4D360UI_AudioVideo"
		"style"					"FlyoutMenuButton"
		"command"				"AudioVideo"
	}

	"BtnController"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnController"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"proportionalToParent"	"1"
		"navUp"					"BtnAudioVideo"
		"navDown"				"BtnStorage"
		"tooltiptext"			"#L4D360UI_Options_Controller"
		"disabled_tooltiptext"	"#L4D360UI_Options_Controller_Disabled"
		"labelText"				"#L4D360UI_Controller"
		"style"					"FlyoutMenuButton"
		"command"				"Controller"
	}

	"BtnStorage"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnStorage"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"proportionalToParent"	"1"
		"navUp"					"BtnController"
		"navDown"				"BtnAudioVideo"
		"tooltiptext"			"#L4D360UI_Options_Storage"
		"disabled_tooltiptext"	"#L4D360UI_Options_Storage_Disabled"
		"labelText"				"#L4D360UI_Storage"
		"style"					"FlyoutMenuButton"
		"command"				"Storage"
	}
}