// auto-generated by io_export_qmap for arch_nucleus

blendbeach_to_beach_wvt_patch
{
	qer_editorimage arch_nucleus_textures/missing_beach_dry.png
	{
		map $lightmap
		rgbgen identity
	}
	{
		map arch_nucleus_textures/missing_beach_dry.png
		blendfunc filter
		rgbgen identity
	}
}

textures/blendbeach_to_beach_wvt_patch
{
	qer_editorimage arch_nucleus_textures/missing_beach_dry.png
	{
		map $lightmap
		rgbgen identity
	}
	{
		map arch_nucleus_textures/missing_beach_dry.png
		blendfunc filter
		rgbgen identity
	}
}
